export const TRANSICIONES = {
    REGISTRADO: ['EN_FIRMAS', 'ANULADO'],
    EN_FIRMAS: ['PRESENTADO', 'OBSERVADO', 'ANULADO'],
    OBSERVADO: ['EN_FIRMAS', 'PRESENTADO', 'ANULADO'],
    PRESENTADO: ['INSCRITO', 'OBSERVADO'],
    INSCRITO: ['CERRADO'],
    CERRADO: [],
    ANULADO: [],
};